
////
This file is generated! See etc/fields.yml and scripts/generate_field_docs.py
////

[[exported-fields]]
== Exported Fields

This document describes the fields that are exported by
ApacheBeat. They are grouped in the
following categories:

* <<exported-fields-env>>
* <<exported-fields-apache_status>>

[[exported-fields-env]]
=== Common Fields

Contains common fields available in all event types.



==== @timestamp

type: date

example: 2015-01-24 14:06:05.071000

format: YYYY-MM-DDTHH:MM:SS.milliZ

required: True

The timestamp of when the measurements were taken. The precision is in milliseconds. The timezone is UTC.


==== type

required: True

Set to "apache-status" to indicate that the statistics are Apache HTTPD server-status.


==== count

type: int

required: True

The number of transactions that this event represents. This is generally the inverse of the sampling rate. For example, for a sample rate of 1/10, the count is 10. The count is used by the UIs to return estimated values. Reserved for future usage.


==== beat.name

Name of the Beat sending the events. If the shipper name is set in the configuration file, then that value is used. If it is not set, the hostname is used.


==== beat.hostname

The hostname as returned by the operating system on which the Beat is running.


[[exported-fields-apache_status]]
=== Apache HTTPD server-status metrics Fields

Contains Apache HTTPD server-status statistics.



=== apache Fields

Contains Apache HTTPD server-status statistics.



==== total_access

type: int

Total access since last restart of Apache HTTPD.


==== total_kbytes.load5

type: int

Total kbytes since last restart of Apache HTTPD.


==== apache.cpu_load

type: float

CPU load.


==== apache.cpu_user

type: float

CPU User.


==== apache.cpu_system

type: float

CPU System.


==== apache.cpu_children_user

type: float

CPU children user.


==== apache.cpu_children_system

type: float

CPU children system.


==== uptime

type: int

Uptime of the Apache HTTPD server.


==== apache.req_per_sec

type: float

Average rate of requests per second since last restart of Apache HTTPD server.


==== apache.bytes_per_sec

type: float

Average rate of bytes per second since last restart of Apache HTTPD server.


==== apache.bytes_per_req

type: float

Average rate of bytes per request since last restart of Apache HTTPD server.


==== busy_workers

type: int

The number of worker serving requests.


==== idle_workers

type: intt

The number of idle worker.


==== conns_total

type: int

Total connections.


==== conns_async_writing

type: int

Total connections 'ConnsAsyncWriting'.


==== conns_async_keep_alive

type: int

Total connections 'ConnsAsyncKeepAlive'.


==== conns_async_closing

type: int

Total connections 'ConnsAsyncClosing'.


==== server_uptime_seconds

type: int

HTTPD Server uptime in seconds.


==== apache.load1

type: float

Load 1.


==== apache.load5

type: float

Load 5.


==== apache.load15

type: float

Load 15.


==== scb_starting_up

type: int

Total workers 'Starting up'.


==== scb_reading_request

type: int

Total workers 'Reading Request'.


==== scb_sending_reply

type: int

Total workers 'Sending Reply'.


==== scb_keepalive

type: int

Total workers 'Keepalive (read)'.


==== scb_dns_lookup

type: int

Total workers 'DNS Lookup'.


==== scb_closing_connection

type: int

Total workers 'Closing connection'.


==== scb_logging

type: int

Total workers 'Logging'.


==== scb_gracefully_finishing

type: int

Total workers 'Gracefully finishing'.


==== scb_idle_cleanup

type: int

Total workers 'Idle cleanup of worker'.


==== scb_open_slot

type: int

Total workers 'Open slot with no current process'.


==== scb_waiting_for_connection

type: int

Total workers 'Waiting for Connection'.


