
////
This file is generated! See etc/fields.yml and scripts/generate_field_docs.py
////

[[exported-fields]]
= Exported Fields

[partintro]

--
This document describes the fields that are exported by Apachebeat. They are
grouped in the following categories:

* <<exported-fields-apachebeat>>
* <<exported-fields-beat>>

--
[[exported-fields-apachebeat]]
== Apachebeat Fields

Contains Apache HTTPD server-status statistics.



[float]
== apache Fields

Contains Apache HTTPD server-status statistics.



[float]
=== totalAccesses

type: integer

Total access since last restart of Apache HTTPD.


[float]
=== totalKBytes

type: long

Total kbytes since last restart of Apache HTTPD.


[float]
=== apache.reqPerSec

type: float

Average rate of requests per second since last restart of Apache HTTPD server.


[float]
=== apache.bytesPerSec

type: float

Average rate of bytes per second since last restart of Apache HTTPD server.


[float]
=== apache.bytesPerReq

type: float

Average rate of bytes per request since last restart of Apache HTTPD server.


[float]
=== busyWorkers

type: integer

The number of worker serving requests.


[float]
=== idleWorkers

type: integer

The number of idle worker.


[float]
== cpu Fields

Contains cpu metrics.



[float]
=== apache.cpu.cpuLoad

type: float

CPU load.


[float]
=== apache.cpu.cpuUser

type: float

CPU User.


[float]
=== apache.cpu.cpuSystem

type: float

CPU System.


[float]
=== apache.cpu.cpuChildrenUser

type: float

CPU children user.


[float]
=== apache.cpu.cpuChildrenSystem

type: float

CPU children system.


[float]
== uptime Fields

Groups uptime metrics.



[float]
=== apache.uptime.uptime

type: integer

Uptime of the Apache HTTPD server.


[float]
=== apache.uptime.serverUptimeSeconds

type: integer

HTTPD Server uptime in seconds.


[float]
== connections Fields

Groups connections metrics.



[float]
=== apache.connections.connsTotal

type: integer

Total connections.


[float]
=== apache.connections.connsAsyncWriting

type: integer

Total connections 'ConnsAsyncWriting'.


[float]
=== apache.connections.connsAsyncKeepAlive

type: integer

Total connections 'ConnsAsyncKeepAlive'.


[float]
=== apache.connections.connsAsyncClosing

type: integer

Total connections 'ConnsAsyncClosing'.


[float]
== load Fields

Contains load metrics.



[float]
=== apache.load.load1

type: float

Load 1.


[float]
=== apache.load.load5

type: float

Load 5.


[float]
=== apache.load.load15

type: float

Load 15.


[float]
== scoreboard Fields

Contains scoreboard metrics.



[float]
=== apache.scoreboard.startingUp

type: integer

Total workers 'Starting up'.


[float]
=== apache.scoreboard.readingRequest

type: integer

Total workers 'Reading Request'.


[float]
=== apache.scoreboard.sendingReply

type: integer

Total workers 'Sending Reply'.


[float]
=== apache.scoreboard.keepalive

type: integer

Total workers 'Keepalive (read)'.


[float]
=== apache.scoreboard.dnsLookup

type: integer

Total workers 'DNS Lookup'.


[float]
=== apache.scoreboard.closingConnection

type: integer

Total workers 'Closing connection'.


[float]
=== apache.scoreboard.logging

type: integer

Total workers 'Logging'.


[float]
=== apache.scoreboard.gracefullyFinishing

type: integer

Total workers 'Gracefully finishing'.


[float]
=== apache.scoreboard.idleCleanup

type: integer

Total workers 'Idle cleanup of worker'.


[float]
=== apache.scoreboard.openSlot

type: integer

Total workers 'Open slot with no current process'.


[float]
=== apache.scoreboard.waitingForConnection

type: integer

Total workers 'Waiting for Connection'.


[float]
=== apache.scoreboard.total

type: integer

Total workers.


[[exported-fields-beat]]
== Beat Fields

Contains common beat fields available in all event types.



[float]
=== beat.name

The name of the Beat sending the log messages. If the Beat name is set in the configuration file, then that value is used. If it is not set, the hostname is used. To set the Beat name, use the `name` option in the configuration file.


[float]
=== beat.hostname

The hostname as returned by the operating system on which the Beat is running.


[float]
=== beat.version

The version of the beat that generated this event.


[float]
=== @timestamp

type: date

example: August 26th 2016, 12:35:53.332

format: date

required: True

The timestamp when the event log record was generated.


[float]
=== tags

Arbitrary tags that can be set per Beat and per transaction type.


[float]
=== fields

type: dict

Contains user configurable fields.


